language: php

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose